baseURL: ""
languageCode: "en-us"
title: "Amit Barde | Sound Designer"
theme: hugo-profile

Paginate: 3
disqusShortname: gurusabarish
googleAnalytics: G-DWJJVE27WD

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1

    #Dropdown menu
    

params:
  title: ""
  description: 
  # staticPath: ""  # The path to serve the static files from
  #favicon: "/fav.png"

  theme:
    disableThemeToggle: false
    # defaultTheme: "light" # dark

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: ""
    title: "Amit Barde"
    subtitle: "Sound Designer"
    content: ""
    #image: /images/hero.svg
    button:
      enable: false
      name: "Resume"
      url: "#"
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-instagram
          url: https://www.instagram.com/amit__barde/
        - icon: fab fa-twitter
          url: https://twitter.com/Amit_Barde
        - icon: fab fa-linkedin
          url: https://nz.linkedin.com/in/amitbarde85
      
      #customIcons:
      # - icon: /fav.png
      #   url: "https://example.com"

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/amit512.png"
    content: |-
      I am a sound designer with experience in linear and interactive media. I have worked on short films, theatre productions, games and interactive installations. I enjoy all aspects of audio, and am always on the lookout for challenging and interesting work. Get in touch to explore how we can collaborate and bring your world - real or virtual - to life with evocative and immersive sounds. 
      
      I am also a researcher with an interest in the use of spatialised audio for information delivery. In addition to this, I am interested in exploring the role of sound in evoking empathy.
  

  # Work
  projects:
    enable: true
    items:
      - title: LightSense | Sounding Design & Implementation
        content: An interactive architectural concept exhibited at ArsElectronica 2021. Implemented using Unity & Wwise.
        image: /images/LightSense.jpg
        featured:
          name: Watch
          link: https://vimeo.com/630391415
         
        #badges:
        #- "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
        links:
          - icon: fab fa-vimeo-v
            url: https://vimeo.com/630391415
          - icon: fas fa-globe
            url: https://www.ars.nz/lightsense/

      - title: Just Bol Do | Sound Design
        content: Just Bol Do is a multi-lingual short film. I was responsible for sound design, foley & the final mix. 
        image: /images/JustBolDo1.jpg
        featured:
          name: Watch
          link: https://vimeo.com/200508248
        # badges:
        #   - "Django"
        #   - "Bootstrap"
        links:
          - icon: fab fa-vimeo-v
            url: https://vimeo.com/200508248

      - title: Zubaani | Music
        content: The title track from Zubaani's self-titled album. I was reponsible for all the recording & mixing
        image: /images/zubaani.jpg
        featured:
          name: Listen
          link: https://vimeo.com/62241505
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
        links:
          - icon: fab fa-vimeo-v
            url: https://vimeo.com/62241505

  #Contact
  contact:
    enable: true
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: amitpbarde@gmail.com
    btnName: Mail me

  footer:
    # recentPosts: false
   
